### ISSUE TITLE
Validate protograph definition

### ISSUE THREAD

**Issue by buchanae** [bmeg/protograph#11]
It would be good to check that the protograph is valid. I had
```
- label: TaskCreatedEvent
  match:
    type: TASK_CREATED
  vertexes:
    - label: Task
      gid: "task:{{id}}"
      splice: task
```

But `splice` is the wrong type. It should be a list. Had to scratch my head for a minute there about why my `data` field was empty.
